### ISSUE TITLE
Working on other webpages 

### ISSUE THREAD

**Issue by ilanafle** [philwinne/nstudy_public#13] opened 2014-07-24 18:06 UTC
I still can't see things from the other webpages I working on on the dashboard (highlighting notes &  my quotes.

**Comment by lfdoherty** [comment] 2014-07-24 18:31
Closed as duplicate of https://github.com/philwinne/nstudy_public/issues/3

If you experience the same problems described in an existing bug, document that with a comment under that bug.

**Closed as completed by lfdoherty** 2014-07-24 18:31 UTC
Labels: duplicate
