### ISSUE TITLE
when I double click a quote to take me to quote on webpage

### ISSUE THREAD

**Issue by zmarzouk** [philwinne/nstudy_public#109] opened 2014-11-03 23:53 UTC
The highlights are shown on the webpage, but the gutter does not show neither do quotes, notes and tags (in the gutter). 
![screen shot 2014-11-03 at 3 53 17 pm](https://cloud.githubusercontent.com/assets/5393395/4892608/9d4ed2fc-63b4-11e4-8765-1648f86d20eb.png)

**Comment by lfdoherty** [comment] 2014-11-04 04:20
I can't reproduce this. Is this only on that specific webpage, or all pages for you? If just this one, what is the URL?

**Comment by zmarzouk** [comment] 2014-11-04 19:50
This is the link 
http://www.sciencedaily.com/releases/2012/10/121009121745.htm#.UZklkXUq_nY.favorites#annotation_b7381bc0_f6d6_e8d2_ba64_9ccec00697fe

**Comment by lfdoherty** [comment] 2014-11-05 01:19
This should be fixed now.

**Closed as completed by lfdoherty** 2014-11-05 01:19 UTC
Labels: unreproduceable
