### ISSUE TITLE
deleting something from the list, won't remove it from the map. 

### ISSUE THREAD

**Issue by ilanafle** [philwinne/nstudy_public#73] opened 2014-10-20 17:32 UTC

**Comment by lfdoherty** [comment] 2014-10-20 20:36
I can't reproduce this, what type of object were you deleting? By delete do you mean "Move to Trash"?

**Comment by ilanafle** [comment] 2014-10-21 16:31
Yes. I selected move to trash, but the item stayed there until I selected remove from map or until I refreshed.

**Comment by lfdoherty** [comment] 2014-10-21 19:18
Duplicate of #84

**Closed as completed by lfdoherty** 2014-10-21 19:18 UTC
Labels: bug
